"""
Type stub (.pyi) generation for IDE support.

Generates Python stub files from MCP tool definitions
for full autocomplete and type checking.
"""

import hashlib
from pathlib import Path
from typing import Any


def generate_stub(
    server_name: str,
    tools: list[Any],
    resources: list[Any],
    prompts: list[Any],
) -> str:
    """
    Generate .pyi stub content for a server.
    
    Args:
        server_name: Name of the server
        tools: List of MCP tools
        resources: List of MCP resources
        prompts: List of MCP prompts
    
    Returns:
        Stub file content as string
    """
    lines = [
        "# Type stubs for MCP server",
        f"# Server: {server_name}",
        "#",
        "# Auto-generated by functional-mcp",
        "",
        "from typing import Any",
        "",
        f"class {server_name.replace(' ', '')}Server:",
        '    """MCP Server Interface"""',
        "",
    ]
    
    # Add tool methods
    for tool in tools:
        tool_name = tool.name
        # Convert to snake_case
        method_name = tool_name.replace("-", "_").replace(" ", "_").lower()
        
        # Get input schema
        input_schema = tool.inputSchema or {}
        properties = input_schema.get("properties", {})
        
        # Build parameter list
        params = []
        for param_name, param_schema in properties.items():
            param_type = param_schema.get("type", "string")
            python_type = {
                "string": "str",
                "number": "float",
                "integer": "int",
                "boolean": "bool",
                "array": "list",
                "object": "dict",
            }.get(param_type, "Any")
            
            params.append(f"{param_name}: {python_type}")
        
        params_str = ", ".join(params) if params else ""
        
        # Add method signature
        lines.append(f"    def {method_name}(self, {params_str}) -> dict[str, Any]:")
        
        # Add docstring
        if tool.description:
            lines.append(f'        """{tool.description}"""')
        
        lines.append("        ...")
        lines.append("")
    
    # Add resource properties
    for resource in resources:
        resource_name = (resource.name or resource.uri.split("/")[-1]).replace("-", "_").upper()
        lines.append(f"    {resource_name}: Any")
        if resource.description:
            lines.append(f'    """{resource.description}"""')
        lines.append("")
    
    # Add prompt functions
    for prompt in prompts:
        prompt_name = prompt.name.replace("-", "_").lower()
        lines.append(f"    def {prompt_name}(self, **kwargs: Any) -> str:")
        if prompt.description:
            lines.append(f'        """{prompt.description}"""')
        lines.append("        ...")
        lines.append("")
    
    # Add utility methods
    lines.extend([
        "    @property",
        "    def tools(self) -> list[Any]:",
        '        """Get tools as callable list for AI SDKs."""',
        "        ...",
        "",
        "    def close(self) -> None:",
        '        """Close server connection."""',
        "        ...",
        "",
    ])
    
    return "\n".join(lines)


def get_stub_cache_path(command: str) -> Path:
    """
    Get cache path for stub file.
    
    Args:
        command: Server command
    
    Returns:
        Path to stub file in cache
    """
    # Hash command to create unique filename
    command_hash = hashlib.md5(command.encode()).hexdigest()[:16]
    cache_dir = Path.home() / ".cache" / "functional-mcp" / "stubs"
    cache_dir.mkdir(parents=True, exist_ok=True)
    
    return cache_dir / f"{command_hash}.pyi"


def save_stub(command: str, content: str) -> Path:
    """
    Save stub to cache.
    
    Args:
        command: Server command
        content: Stub file content
    
    Returns:
        Path where stub was saved
    """
    path = get_stub_cache_path(command)
    path.write_text(content)
    return path


__all__ = ["generate_stub", "get_stub_cache_path", "save_stub"]

